### ISSUE TITLE
No files mounted when tar uses relative paths

### ISSUE THREAD

**Issue by Jamedjo** [mxmlnkn/ratarmount#1]
All the files appear to have been mounted within an unreachable '.' folder, with the index file listing the them as being at locations like `/./.config`.

The `tar.gz` was generated on osx with a relative path given as well as a list of folders to exclude.

**Comment by mxmlnkn** [comment]
I'm not sure if it is exactly the same problem, but I can reproduce this with these steps:

```shell
cd -- "$( mktemp -d )"
echo foo > bar
tar cf normal.tar bar
tar tf normal.tar 
    bar
tar cf relative.tar ./bar
tar tf relative.tar 
    ./bar
mkdir -p a/b/c
cd -- "$_"
echo foo > bar
tar cf convoluted.tar ./../../b/././c/.././c/bar
    tar: Removing leading `./../../b/././c/../' from member names
tar tf convoluted.tar
    ./c/bar
tar cf relative2.tar ../bar
    tar: Removing leading `../' from member names
tar tf relative2.tar 
    c/bar
cd -- "$_"
```

Now, trying to mount it:

```
ratarmount.py normal.tar 
    Creating offset dictionary for normal.tar ...
    Creating offset dictionary for normal.tar took 0.00s
cat normal/bar
    foo
ratarmount.py relativetar 
ls -la relative
    total 4
    dr-xr-xr-x 2 user user 10240 Apr 19 12:39 .
    dr-xr-xr-x 2 user user 10240 Apr 19 12:39 .
    drwx------ 5 user user  4096 Apr 19 12:47 ..
cat relative/./bar
    cat: relative/./bar: Read-only file system
cat relative/bar
    cat: relative/bar: Read-only file system
```

Commit 7e139fe743aefb250950e01c112efb5b5e04adc0 should fix this by normalizing all paths.
You will have to remove the created index though so that it can be newly created without the leading `./`.
I added a command line option `-r|--recreate-index`, which should also work instead of removing the index manually.

If that does not fix your problem the issue should be reopened and could you provide a minimal non-working tar, e.g., only containing one `foo` file with a contents `bar`?

**Comment by Jamedjo** [comment]
Thanks!

I'd managed to get a hacky workaround but will retry with your patch.

The `--recreate-index` flag will come in handy and reminds me I was hoping for a "don't recursively untar" option since this was a backup of my home directory including random tar files.

The fix I used was:

```
diff --git a/ratarmount.py b/ratarmount.py
old mode 100644
new mode 100755
index 89c4cd7..6d6cd83
--- a/ratarmount.py
+++ b/ratarmount.py
@@ -133,7 +133,7 @@ class IndexedTar:
                 indexedTar = IndexedTar( tarInfo.name, fileObject = fileObject, writeIndex = False )
                 fileObject.seek( fileObject.tell() ) # might be especially necessary if the .tar is not actually a tar!
 
-            path = "/" + tarInfo.name
+            path = "/" + re.sub(r"^\./", "", tarInfo.name)
 
             if indexedTar is not None and ( indexedTar.dirIndex or indexedTar.fileIndex ):
                 # actually apply the recursive tar mounting
```

**Comment by Jamedjo** [comment]
With you patch I get "Input/output error" attempting to list the directory:

```
~/Software/ratarmount$ ls -l ~/osx_backup_2019-04-17.tar
ls: reading directory '/home/james/osx_backup_2019-04-17.tar': Input/output error
total 0
~/Software/ratarmount$ ls -al ~/osx_backup_2019-04-17.tar
ls: reading directory '/home/james/osx_backup_2019-04-17.tar': Input/output error
total 4
dr-xr-xr-x  2 james james   7717335652 Apr 17 19:03 .
-r-xr-xr-x  2   501 dialout        228 Apr 17 18:21 ._.
drwxr-xr-x 36 james james         4096 Apr 20 03:32 ..
```

**Comment by Jamedjo** [comment]
I'll try and create a minimal tar, but can also give an example of `tarInfo.name`:

```
~/Software/ratarmount$ python3 -m pdb ~/Software/ratarmount/ratarmount.py ~/osx_backup_2019-04-17.tar.gz
> /home/james/Software/ratarmount/ratarmount.py(3)<module>()
-> import os, re, sys, stat, tarfile, pickle, fuse, argparse
(Pdb) b 159
Breakpoint 1 at /home/james/Software/ratarmount/ratarmount.py:159
(Pdb) c
(Pdb) tarInfo.name
'./team-quiz'
(Pdb) os.path.normpath("/" + tarInfo.name)
'/team-quiz'
(Pdb) os.path.normpath(tarInfo.name)
'team-quiz'
```

**Comment by Jamedjo** [comment]
Non working tar: [example.tar.gz](https://github.com/mxmlnkn/ratarmount/files/3099711/example.tar.gz)

**Comment by mxmlnkn** [comment]
The example.tar.gz is compressed. This is currently not supported. I added a warning message and avoided mounting an empty directory in case a compressed archive is specified. I was looking into combining ratarmount with [lzopfs](https://github.com/mxmlnkn/lzopfs) in order to add support for compressed archives but currently I don't have the incentive as I don't need it.

The problem with your TAR in comparison to my self created TARs with leading `./` is that it contains `./`. I.e., output for `tar tvf` for my test TAR:

    -rw-r--r-- user   4 2019-04-19 12:38 ./bar

your test TAR:

    drwxr-xr-x user 0 2019-04-20 04:52 ./
    -rw-r--r-- user 8 2019-04-20 04:52 ./file
    drwxr-xr-x user 0 2019-04-20 04:52 ./somefolder/
    -rw-r--r-- user 2 2019-04-20 04:52 ./somefolder/file

The problematic entry being the topmost one. It seems such a TAR can be created with:

    tar --owner=user --group=group -cf ../foo.tar ./

Could you test the latest commit?
