### ISSUE TITLE
Dependency fusepy

### ISSUE THREAD

**Issue by RubenKelevra** [mxmlnkn/ratarmount#101]
fusepy is currently a dependency of ratarmount. I was wondering if a switch to e.g. regular fuse-python is possible or planned?

fusepy has not been touched for years now, and there are still plenty of issues raised in https://github.com/fusepy/fusepy/issues/134

**Comment by mxmlnkn** [comment]
Yes, especially FUSE 3 support would be desirable. But because the API changes too much it seemed difficult to port the complexity of ratarmount to it especially because the API was not file path based anymore, I think? I didn't take a really hard look at it yet.

I am aware though that fusepy is practically dead but unfortunately the two or so forks also died out fast. And the [last time I looked](https://stackoverflow.com/a/52943795/2191065) fuse-python also didn't look very alive either.

Is fuse-python the Python FUSE binding you would recommend? I think I would have looked into [pyfuse3](https://github.com/libfuse/pyfuse3) instead but I think it has the aforementioned problems making a port hard.

**Comment by mxmlnkn** [comment]
I have decided to simply bundle fuse.py into ratarmount / [fork it](https://github.com/mxmlnkn/fusepy). It's not rocket science and the fuse.py file has a very managable size with less than 2k lines of code. I have [added](https://github.com/fusepy/fusepy/pull/148) simple [FUSE 3 support](https://github.com/mxmlnkn/ratarmount/commit/1a1a4d1602cf268d7738001e460336c4729e0623) and all ratarmount tests [have run successfully](https://github.com/mxmlnkn/ratarmount/commit/bd13bb199f897ffb0a6fded1ef316b3cc3c729dd) with a FUSE 3 shared library.

Adding FUSE 3 support is not as hard as it sounds. Mostly, some deprecated functions, unused by fusepy, were removed, some arguments added to some callbacks and some new methods added, which do not have to be used. Some FUSE 3 minor version changes have similarly bad ABI changes as this major version break. FUSE 2 vs. 3 is not a FUSE kernel level API change but a change in the relatively lean [libfuse](https://github.com/libfuse/libfuse) wrapper, only. The default will still be to try to load FUSE 2 first because of its stability and only if that was not found, use libfuse3.

With the prioritization of FUSE 2, FUSE 3 only being used as a fallback, all of the extensive ratarmount tests running fine, I'd say that this can be merged for the next ratarmount non-bugfix version. It would still be nice to have more tests in the fusepy fork itself. Having such tests was the reason why the refuse fork fizzled out, so I wouldn't make it a requirement for further development though. Alternatively it might be nice to find fusepy-dependendent project and run their tests in the fusepy fork.

And as always, if some other fusepy user reads this. Help for maintaining the fork, testing on other platforms, or simply a second pair of exes for reviewing my changes is highly wanted.
