### ISSUE TITLE
Can I commit to the original tar files? / commit-overlay in the Readme commiting to tar read-only?

### ISSUE THREAD

**Issue by zDEFz** [mxmlnkn/ratarmount#103]
` --commit-overlay` states ```Apply deletions and content modifications done in the write overlay to the
                        archive. (default: False)```
`-w WRITE_OVERLAY, --write-overlay WRITE_OVERLAY` states 
```
       Specify an existing folder to be used as a write overlay. The folder
                        itself will be union-mounted on top such that files in this folder take
                        precedence over all other existing ones. Furthermore, all file creations
                        and modifications will be forwarded to files in this folder. Modifying a
                        file inside a TAR will copy that file to the overlay folder and apply the
                        modification to that writable copy. Deleting files or folders will update
                        the hidden metadata database inside the overlay folder. (default: None)
```

However, will the modifications be applied to the original tar archives, or are they at all times read-only?

**Comment by zDEFz** [comment]
Thank you so much. Before you add this usage, please rename `--commit-overay` to `--commit-overlay`

**Comment by mxmlnkn** [comment]
Thanks for pointing out the typo.

I tested it out and I noticed that the output after conforming with `commit` is:

> Committed successfully. You can now remove the overlay folder at zlib-wiki-overlay.

So, you don't need to copy the overlay folder because, contrary to my expectation, it is not deleted automatically. I guess I was very fearful of deleting anything and I still am. A read-only tool has much less potential for data corruption than tools that modify ...

**Comment by zDEFz** [comment]
I see. My interest in the tool just dropped by a lot, though I really appreciate the ability to just mount big archives instead of extracting them. I think some of the biggest hurdles would be using something like python.xz, cause I seem to have to dig for it, theres no UI, theres just some ... well say, scarce documentation / examples. Next thing, random-access doesn't make too much sense on HDD's anyways, does it?

But really, my motivation or interest was, that I no more have to send many files over the lan, just one. But I listen to you, to not use such formats as a daily containerized format.

**Comment by mxmlnkn** [comment]
That's unfortunate to hear but I agree that ratarmount is not well-suited for modifying archives. The support for that is very barebones right now. I'm not sure what you mean with python.xz. XZ-compressed archives are supported but it is one of the problematic (slower and memory-intensive) compression backends. Bzip2 compression or gzip work much better. Zstd and xz only workw well when compressed correctly, see [t2sz](https://github.com/martinellimarco/t2sz) or [pixz](https://github.com/vasi/pixz).

> Next thing, random-access doesn't make too much sense on HDD's anyways, does it?

It does very much so. The alternative before was to use archivemount and it would take minutes to hours to first open a large (10 GB+) tar archive and every file access would then again also take minutes to hours. This was mainly a programming bug and a correct implementation like ratarmount can do it in seconds. [fuse-archive](https://github.com/google/fuse-archive) is a more direct alternative to archivemount because it also uses libarchive as backend but fixes that performance bug. It does not have the index though, which means that opening an archive, especially on HDDs, can still take hours as opposed to simply loading the index with ratarmount.

 > But I listen to you, to not use such formats as a daily containerized format.

Yeah, I guess SquashFS or maybe even ZIP or an ext4/ntfs-formatted image file would be a better alternative when you need to modify often. Personally, I use it for very large data dumps that I'll never have to modify again such as backups or training data sets for machine learning like a dump of Wikipedia.
