### ISSUE TITLE
Support for securetar

### ISSUE THREAD

**Issue by RubenKelevra** [mxmlnkn/ratarmount#111]
[Home Assistant](https://www.home-assistant.io/) uses encrypted tar files, which they call [securetar](https://github.com/pvizeli/securetar), for their backups.

So you get a tar file, and in it there are files with '.tar.gz' extension, but they are actually encrypted.

If using `--recursion-depth 1` on the main tar file, you end up with errors for each securetar-file:

```console
[Warning] Mounting of '/xzy.tar.gz' failed because of: Archive to open (<StenciledFile>) has unrecognized format!
```

It would be nice if ratarmount could be supplied with the necessary password and decrypt on-the-fly those tar files to mount them.

Here's an [example how Home Assistant opens them for reading](https://github.com/home-assistant/supervisor/blob/3ceec044a80d40902757b5088bc1ad71ae911411/supervisor/backups/backup.py#L367).

**Comment by mxmlnkn** [comment]
This looks like a **very** new "format". It simply is a raw AES encrypted file. There aren't even any magic bytes for file identification :/. Probably not so important because I'm using the file extension for speed anyway. But it still makes file handling harder requiring me to do trial-and-error instead of proper dispatch. It might be possible to do some entropy analysis on the first 4 KiB as a heuristic detection. It should be quasi-random if it is encrypted.

**Comment by mxmlnkn** [comment]
I was able to decrypt the file in a proof of concept 6fcbf96624f74e245baf2dd9b05b1e9323f11c4f but I encountered an unexpected exception when trying to use the fully decrypted buffer further. I will have to look into this at a later time.

Aside from that, the implementation is not performant because it fully decrypts the file. An optimal solution would provide seeking and on-the-fly decryption.

**Comment by mxmlnkn** [comment]
I investigated further. The exception message wasn't very elucidating but the problem seems to be a rather simple "corrupt gzip file" issue.

I have no idea how this securetar format is supposed to work correctly, at least for the compressed case. It might be that it happens to work for non-compressed files because tarfile only writes in the required multiples of 16 B (likely multiples of 512 B). But, for compressed files, which was the default when using securetar, I don't see how it would work.

I have opened an [issue](https://github.com/pvizeli/securetar/issues/19) in the securetar repository.

For a non-compressed archive, the state from yesterday already works fine. You can try the latest development version like this:

```bash
python3 -m pip install --user securetar
python3 -m pip install --user --force-reinstall \
    'git+https://github.com/mxmlnkn/ratarmount.git@develop#egginfo=ratarmountcore&subdirectory=core' \
    'git+https://github.com/mxmlnkn/ratarmount.git@develop#egginfo=ratarmount'

mkdir -p a/b
echo pragzip > a/b/pragzip
python3 -c '
import pathlib; import securetar
with securetar.SecureTarFile("non-compressed-securetar.tar", "w", b"passwordpasswordpasswordpassword", gzip=False) as tarFile:
    securetar.atomic_contents_add(tarFile, pathlib.Path("a/"), excludes=[], arcname=".")
'

ratarmount non-compressed-securetar.tar mounted
tree mounted
#    mounted
#    └── b
#        └── pragzip
cat mounted/b/pragzip
# pragzip
```
