### ISSUE TITLE
Compressed index?

### ISSUE THREAD

**Issue by peteruhrig** [mxmlnkn/ratarmount#115]
I was wondering whether compressed indexes are available, and if not, put this in as a suggestion for a new feature.

In my application, I have files of around 200 MB, for which ratarmount creates a 40 MB index. So basically, we're adding a 20% overhead. With bzip2, that index file compresses down to 2.9 MB, reducing the overhead to 1.5%. This makes a huge difference, because we have a few hundred thousand archives. Since you already have really fast decompression algorithms in place, the overhead in processing time might be acceptable for many applications.

**Comment by mxmlnkn** [comment]
They are not available. A feature like this would be welcome. It would have been nice to have this included directly in SQLite but it seems like it is not easily possible with the standard version but there exists the proprietary extension ZIPVFS.

It would be kinda cool to compress the sqlite database and then use one of the new backends, such as indexed_bzip2, pragzip, or indexed_zstd, probably the last one. One problem will be write support, but it might be easy to compress it as a post-process step after the index has been created. Would that work for you? As a first step, I might even simply support reading of such compressed indexes while not yet implementing automatic compression. The user could then simply compress it manually if they want. This would also be useful for initial performance benchmarks.

**Comment by mxmlnkn** [comment]
I looked a bit into the second solution. On-the-fly access is difficult because Python's sqlite module only wants to work with file paths (or :memory:). Therefore, I can't simply open an IndexedGzipFile or similar file object and give it to sqlite. I would have to either FUSE mount the index via a separate process or extract it into /tmp while the SQLite index is being used.

**Comment by mxmlnkn** [comment]
> In my application, I have files of around 200 MB, for which ratarmount creates a 40 MB index.

Are those gzip-compressed TAR archives? The index for gzip files is the largest. The tradeoff between index size and seek access latency can be configured with the `--gzip-seek-point-spacing` option. A higher spacing between seek points increases the seek latency but reduces the index size because each gzip seek point requires storing 32 KiB of data. For bzip2, each seek point is only 16 B. Zstandard might also work better but for seeking to work with Zstandard you have to compress it with pzstd instead of zstd or ensure otherwise that the zstandard file contains [multiple frames](https://github.com/mxmlnkn/ratarmount#xz-and-zst-files).

**Comment by peteruhrig** [comment]
No, these are bzip2 compressed TAR archives. I have made one available to you via email.

**Comment by mxmlnkn** [comment]
Thank you. I really was offtrack. That really is some interesting outlier file useful for optimization. It simply has too many small files >.< even if that is one of the intended use cases for ratarmount. Some statistics using SQLite:

 - ~200k files `SELECT COUNT(*) FROM files;`
 - ~4 kB average size `SELECT AVG(size) FROM files;`
 - compression ratio: ~5 `python3 -c "print( $( rapidgzip --count "$file" ) / $( stat -c %s -- "$file" ))"`
 - ~1 kB compressed average size
 - ~100 B average path length `SELECT AVG(LENGTH(path)+LENGTH(name)) FROM files;`
 - Total bytes required for all file paths: 24 MB `SELECT SUM(LENGTH(path) + LENGTH(name)) FROM files` 

The average path length compared to the average compressed file size, already gives you the correct ballpark, i.e., an overhead of ~10%.

This would really require some kind of short string compression inside SQLite, or compressing the whole index. Unfortunately, it is really hard to add transparent decompression because SQLite only wants to work with real file descriptors and not Python file objects. I.e., an option would be to decompress the index into `/tmp` and use it from there. This would reduce the storage overhead but adds some overhead for mounting the index because it has to be decompressed each time it is mounted. That shouldn't be too bad though, maybe 1-10 seconds.

Alternatively, what you could do until this is implemented, you could try to reduce the path lengths. In your case, all files are in a single subfolder. You could get rid of that subfolder with:

```bash
rm "$file.index.sqlite"
ratarmount --transform '[^/]*/' '' "$file"
```

This already reduces the index size from 65 MB down to 40 MB for me and has the additional benefit that one useless subfolder is cut out.

You could even get rid of the shared prefix for all of the files so that you end up with files simply named `000001.json` until `200000.json`.

```bash
rm "$file.index.sqlite"
ratarmount --transform '[^/]*/.{36}' '' "$file"
```

This reduces the index file down to 23 MB for me, i.e., 100% overhead... Well, this probably is still insufficient.

I guess, I'll implement the limited support for compressed index files as outlined above by extracting them to /tmp or ~/.cache/ratarmount while they are used for active mounts.

**Comment by mxmlnkn** [comment]
I have pushed support for existing compressed indexes. These indexes are not created by ratarmount, but have to be compressed manually with `gzip`, `bzip2`, `pzstd`, or any tool of your choice. And they will be temporarily fully decompressed before being used for mounting. You can try it out with:

```bash
python3 -m pip install --user --force-reinstall \
    'git+https://github.com/mxmlnkn/ratarmount.git@master#egginfo=ratarmountcore&subdirectory=core' \
    'git+https://github.com/mxmlnkn/ratarmount.git@master#egginfo=ratarmount'
```

**Comment by mxmlnkn** [comment]
> This already reduces the index size from 65 MB down to 40 MB for me and has the additional benefit that one useless subfolder is cut out.

The same can be achieved transparently with this:

```sql
SELECT name FROM sqlite_master WHERE type="table";
ALTER TABLE "files" RENAME TO "filesold";
SELECT name FROM sqlite_master WHERE type="table";

CREATE TABLE IF NOT EXISTS "filesdata" (
    "pathid"        INTEGER NOT NULL,  /* path with leading and without trailing slash */
    "name"          VARCHAR(65535) NOT NULL,
    "offsetheader"  INTEGER,  /* seek offset from TAR file where the TAR metadata for this file resides */
    "offset"        INTEGER,  /* seek offset from TAR file where these file's contents resides */
    "size"          INTEGER,
    "mtime"         REAL,
    "mode"          INTEGER,
    "type"          INTEGER,
    "linkname"      VARCHAR(65535),
    "uid"           INTEGER,
    "gid"           INTEGER,
    /* True for valid TAR files. Internally used to determine where to mount recursive TAR files. */
    "istar"         BOOL   ,
    "issparse"      BOOL   ,  /* for sparse files the file size refers to the expanded size! */
    /* See SQL benchmarks for decision on the primary key.
     * See also https://www.sqlite.org/optoverview.html
     * (path,name) tuples might appear multiple times in a TAR if it got updated.
     * In order to also be able to show older versions, we need to add
     * the offsetheader column to the primary key. */
    PRIMARY KEY (pathid,name,offsetheader)
);

CREATE TABLE "paths" ( "value" VARCHAR(65535) PRIMARY KEY );
CREATE VIEW "files" (
        "path"        , 
        "name"        , 
        "offsetheader", 
        "offset"      , 
        "size"        , 
        "mtime"       , 
        "mode"        , 
        "type"        , 
        "linkname"    , 
        "uid"         , 
        "gid"         , 
        "istar"       , 
        "issparse"    
    ) AS SELECT p.value, name, offsetheader, offset, size, mtime, mode, type, linkname, uid, gid, istar, issparse
    FROM "filesdata" AS f
    INNER JOIN paths AS p ON p.rowid = f.pathid;

INSERT OR IGNORE INTO paths(value) SELECT DISTINCT "path" FROM "filesold" ORDER BY "path";
INSERT INTO filesdata SELECT 
        p.rowid       ,
        "name"        ,
        "offsetheader",
        "offset"      ,
        "size"        ,
        "mtime"       ,
        "mode"        ,
        "type"        ,
        "linkname"    ,
        "uid"         ,
        "gid"         ,
        "istar"       ,
        "issparse"    
    FROM "filesold" as f 
    INNER JOIN paths AS p ON p.value = f.path;

SELECT COUNT(*) FROM filesold;
SELECT COUNT(*) FROM filesdata;
SELECT COUNT(*) FROM files;

DROP TABLE "filesold";

VACUUM;

DROP TRIGGER IF EXISTS "files_insert";
CREATE TRIGGER "files_insert" INSTEAD OF INSERT ON "files2" BEGIN
    INSERT OR IGNORE INTO paths(value) VALUES (NEW.path);
    INSERT OR IGNORE INTO filesdata(pathid) VALUES(
        (SELECT paths.rowid FROM paths WHERE value = NEW.path)
    );
END;    
```

Unfortunately, older ratarmount versions won't accept this and will try to recreate the index from scratch because my consistency check was too strict and did check for a `files` table, which does not accept views. It would have worked with this change:

```diff
diff --git a/core/ratarmountcore/SQLiteIndex.py b/core/ratarmountcore/SQLiteIndex.py
index 76956dbc..f8904885 100644
--- a/core/ratarmountcore/SQLiteIndex.py
+++ b/core/ratarmountcore/SQLiteIndex.py
@@ -53,7 +53,7 @@ from .utils import (
 
 
 def getSqliteTables(connection: sqlite3.Connection):
-    return [x[0] for x in connection.execute('SELECT name FROM sqlite_master WHERE type="table"')]
+    return [x[0] for x in connection.execute('SELECT name FROM sqlite_master WHERE type="table" OR type="view"')]
 
 
 def _toVersionTuple(version: str) -> Optional[Tuple[int, int, int]]:
```

This is unfortunate. It would have been nice if there was something like `CREATE TRIGGER` on `SELECT` statements.

But, I guess it also is not too bad because the size improvements are "only" 2x even for this extreme use case. Although it is also extreme for having very long file names with overlapping prefixes. Normally, you would simply name files like `00001.jpg`.

Furthermore, there are trade-offs:
 - It seems to worsen complexity. While the insertion complexity is `O(number of rows)` since my [last optimization](https://github.com/mxmlnkn/ratarmount/blob/master/benchmarks/plots/sqlite%20primary%20key%20benchmark%2010000k%20files%20insert.png#database-sizes-over-row-count), it will degrade to `O(n log(n))` again when using views. I tried everything I could think of to avoid this but nothing seemed to work. In the first place, it is weird that the current state is basically `O(n)`, which got **improved** to this, not worsened(!), by the `ORDER BY (path,name)` clause. The `ORDER BY` would normally imply at least `O(n log(n))` for sorting, and there is also the fact that sqlite uses B-tree at least for the pages, but sorted B-tree inserted insertion may be `O(1)`, I'm not sure... Very weird.
 - I assume that it partly must be slower because the lookup of string-to-ID will be `O(log(n))` for bisection, which seems to somewhat match my select benchmarks, but I am not sure whether it only starts to become `O(log(n))` when it has to traverse the page B-tree. It already slows down after ~30k rows. Searching online, it seems that there is no `O(1)` lookup possible with libsqlite as would be the case with a hash-map, at least because of the B-tree structure.
 - If there are many duplicates, then insertion and even selecting will be faster! I'm not entirely sure why selecting will be faster. I had somehow hoped that libsqlite implements some kind of string hashing but maybe it does full string comparison so that a one-time map to integer and subsequent lookup will be faster. While the speedup seems to grow `O(log(n))`, the performance improvements for this for < 10M rows would still be smaller than 30%, so also not life-changing.
 - While `path` will very likely be very compressible because there will almost always be more than one file per folder, this may not be true for file names. For this reason and the possible performance overhead, I am undecided whether to deduplicate file name strings.

![Image](https://github.com/user-attachments/assets/3914ccce-803b-42d2-8f4a-a51fcc18519e)

![Image](https://github.com/user-attachments/assets/03295f70-67e7-437b-9a5a-edd0e002a4cf)

![Image](https://github.com/user-attachments/assets/05094c8d-15be-4991-99c7-73e0ba29f9c6)
