### ISSUE TITLE
Use mmap or GDBM for indexes to save memory

### ISSUE THREAD

**Issue by ole-tange** [mxmlnkn/ratarmount#12]
Having the index in memory makes access fast. But the whole idea ratarmount is to be able to access a few files, so it is a waste of memory to keep the index in memory for all files.

Python has mmap support, so it ought to be possible to store the index as a mmap file. That way the system will only read the relevant parts of the index from disk, and virtual memory management will work for you.

Another alternative to mmap is GDBM: This may make it easier to do { key => value } than mmap can, and it will make the index work cross platform (whereas the mmap would only work on the platform it was built).

One way to do this would be to serialize every FileInfo object and save those as values for each key. When a key is needed, fetch the value and deserialize it. It may make the index file bigger, but memory requirements and startup time will be lower, as you will only have a single FileInfo object in memory at a time.

**Comment by mxmlnkn** [comment]
That's something I didn't think of as I was just glad it worked in the first place. Recently, I did some personal scripts using the sqlite3 python module. I think this also might be a viable alternative similar to what you suggested with GDBM? I think that would also fix the (de)serialization problems I had so much trouble with.

**Comment by ole-tange** [comment]
Yup, sqlite3 would solve the same problem just fine, and if you are already comfortable with SQLite, then that may be easier for you to get working. I would expect SQLite to cost more CPU (as SQL is more general than GDBM), but since data will be read from disk, then disk will be the limiting factor in both cases.

**Comment by mxmlnkn** [comment]
Some benchmarks:

**Memory usage over time for index creation SQLite vs. custom (default)**

![resident-memory-over-time-saving-64-MiB-metadata](https://user-images.githubusercontent.com/6842824/69000529-760d6d80-08d1-11ea-9c2c-1e1a6616a437.png)

**Memory usage over time for index loading SQLite vs. custom (default)**

![resident-memory-over-time-loading-64-MiB-metadata](https://user-images.githubusercontent.com/6842824/69000528-73127d00-08d1-11ea-9cef-242bd062e6a3.png)

The SQLite version is ~10% slower and the created index files are ~2x larger but as can be seen the peak memory usage is now bounded (and configurable in the code). For the above plots I configured it to 16MB.

For the default in the release, I'm going to set it to 512 MB because most will have that amount of memory at least if they are dealing with such large TARs.  The SQL database is twice the size presumably because SQLite stores a kind of sorting map when a VARCHAR PRIMARY KEY is used. When using an INTEGER id as PRIMARY KEY, the SQL database would be half the size of what it is now, see benchmarks below.

Index loading is now basically non-existent because it is directly read from file. I still need to benchmark some `ls -la` calls and I might have to cache some results. Below are benchmarks for SQL SELECT statements, for 16M files they are roughly 1ms. So, for a folder with 1000 files, it should at least take 1s for the listing, which is kinda meh. Instead I might be able to cache the SELECT statement for the whole folder. SQL does not seem to do this kind of caching.

**Pure SQL database benchmark with 2M rows / files**

![sqlite primary key benchmark 2000k files](https://user-images.githubusercontent.com/6842824/69000572-2e3b1600-08d2-11ea-84dd-d5e4caf8d679.png)

**Pure SQL database benchmark with 10M rows / files**

![sqlite primary key benchmark 10000k files](https://user-images.githubusercontent.com/6842824/69000580-41e67c80-08d2-11ea-8867-c19f7febed97.png)

For row counts > 2M, the database creation degrades quite a lot because each cache spill seems to trigger a complete resorting of the newly added values in memory into the existing database on disk, or something like that. Still, the total time to insert 10M rows is ~7min, so compared to my earlier benchmarks of the ILSVRC dataset, which has 2M images and took 45min to create, the SQL database creation should not be a too significant overhead.

**Database sizes over row count**

![sqlite primary key benchmark sizes over row count](https://user-images.githubusercontent.com/6842824/69000587-65112c00-08d2-11ea-8f0f-d613c005010f.png)

As can be seen, the INTEGER primary key version results in much smaller database files.

**Scaling in respect to row count**

![sqlite primary key benchmark times over row count](https://user-images.githubusercontent.com/6842824/69000593-7ce8b000-08d2-11ea-85cc-6b14fcf0f0fb.png)

I concluded that the VARCHAR PRIMARY key version was the only real option for usable lookup times for the mounted FUSE system and I'll do hell to avoid all conditions except equality as only that one seems to be able to capitalize on the sortedness and actually does a bisection search and scales with O(log n). All other statements are ~10k times slower for the case with 2M rows. This kind of gap even made benchmarking kinda awkward.

**Comment by ole-tange** [comment]
The graphs for memory usage look good.

I do not quite get the situation with 2M rows. If I understand you correctly you create the table with index and when you add more rows than 2M, the performance degrades.

If that is the case, try creating without index, and add the index _after_ adding all the rows. That should only sort the data once.

Do you have numbers to back up the choice of 512 MB? There is a risk you will be using 512 MB of RAM + 512 MB of disk cache when you could have just used 512 MB disk cache. In other words: Does it actually help? And what happens if you are low on memory?

If you are using full path as the key, you will be storing the dirname for each file. This could be avoided by using something similar to an inode.

When caching the file infos for a full folder, did you cache them deserialized or serialized? Maybe the deserialization is costly?

**Comment by mxmlnkn** [comment]
Note: All the benchmarks in my last post were created with [benchmarkSqlite.py](https://github.com/mxmlnkn/ratarmount/blob/master/benchmarks/benchmarkSqlite.py), you can look there for exact details.

> Do you have numbers to back up the choice of 512 MB? There is a risk you will be using 512 MB of RAM + 512 MB of disk cache when you could have just used 512 MB disk cache. In other words: Does it actually help? And what happens if you are low on memory?

The cache size was only tested manually. In general, it seems, the higher the faster the insertion is. The default cache size for my SQL version seems to be 2MB. Here is a quick plot for the total insertion time rows over cache size.

** 128 000 files **

![sqlite cache size benchmark 128k files](https://user-images.githubusercontent.com/6842824/69227905-f3abd480-0b82-11ea-95af-86460e1b73da.png)

** 1 000 000 files **

![sqlite cache size benchmark 1000k files](https://user-images.githubusercontent.com/6842824/69227935-fd353c80-0b82-11ea-8acd-c36961e9c769.png)

As can be seen, the higher the cache size, the better. And obviously, the larger the data is, the more it will profit from higher cache sizes.

If you are low on memory, my system freezes because my OOM killer is not working well enough, but normally the program would be killed as soon as the cache has been filled up. The cache grows during the INSERT statements. So, if your TAR is small enough, the cache is transparent / won't be allocated. The python sqlite3 module does not seem to be intelligent enough to automatically reduce the cache size. I could add  a command line option or some kind of intelligent logic, like: use at most half of the free RAM, actually I'll add that check, it can't hurt.

> When caching the file infos for a full folder, did you cache them deserialized or serialized? Maybe the deserialization is costly?

It's not serialized as SQL can do that for me. Therefore, a simple call to `readdir` is pretty fast. However, most tools like `find` or `ls` (even without the `-l` option) seem to call `stat` for each file inside the folder, which currently triggers a SQL SELECT statement each, imo that's not so much my problem and also slow on traditional file systems. I tried to cache it but it gets even slower. At this point it would be better to move on to Cython or directly C, I think.

Directly using the data from the SQL table requires some logic changes though. Because of this the SQLite version is actually it's own standalone class `SQLiteIndexedTar` and I'm thinking about deprecating the other serialization schemes. The only thing they have is a 10% speedup and lower disk usage, which imo shouldn't be a problem as it's  very small compared to the original TAR. E.g., ILSVRC dataset 150GB, SQLite index size 146MB.

This is actually the SQL scheme used:

```sql
CREATE TABLE "files" (
    "path"     VARCHAR(65535) NOT NULL,
    "name"     VARCHAR(65535) NOT NULL,
    "offset"   INTEGER,  /* seek offset from TAR file where these file's contents resides */
    "size"     INTEGER,
    "mtime"    INTEGER,
    "mode"     INTEGER,
    "type"     INTEGER,
    "linkname" VARCHAR(65535),
    "uid"      INTEGER,
    "gid"      INTEGER,
    /* True for valid TAR files. Internally used to determine where to mount recursive TAR files. */
    "istar"    BOOL,
    PRIMARY KEY ( path, name ) /* see SQL benchmarks for decision on this */
);
```

> If that is the case, try creating without index, and add the index _after_ adding all the rows. That should only sort the data once.

I'm not sure I understand this completely. The index would be the Primary Key, I guess. The primary key can't really be changed. However, I can create a new table and copy all data into that new table and then delete the old one. Even moving data does not seem to be supported, so disk requirements would double because of the peak, which again, might not be a problem at all compared to the original huge TAR. This is how it basically would look like:

```SQL
CREATE TABLE "files_tmp" ( 
    "id" INTEGER PRIMARY KEY, 
    "path" VARCHAR(65535), 
    "name" VARCHAR(65535) 
);
INSERT INTO files VALUES 
    (0,"abcdef", "ghijklmn"), 
    (1,"opqrst","uvwxyz"), 
    (2,"abcdef", "ghijklmn");
CREATE TABLE "files" (
    "path" VARCHAR(65535),
    "name" VARCHAR(65535),
    PRIMARY KEY (path,name)
);
INSERT INTO "files" (path,name) 
    SELECT path,name FROM "files_tmp" 
    ORDER BY path,name; # I only added this for the second plot below but it improves a lot!
DROP TABLE "files_tmp";
```

Here is a quick benchmark for 1M rows (again over the cache size, just for fun. Benchmark without the ORDER BY):

![sqlite using intermediary table cache size benchmark 1000k files](https://user-images.githubusercontent.com/6842824/69230059-e2fd5d80-0b86-11ea-9cc6-92832475310d.png)

So yeah, using an intermediary table does not seem to make anything better, actually even worse by ~10%. 

Here is another plot, this time with the ORDER BY statement when moving data to the new sorted table:

![sqlite using intermediary table order by cache size benchmark 1000k files](https://user-images.githubusercontent.com/6842824/69230232-28ba2600-0b87-11ea-91b1-6dea1612136e.png)

Finally, pretty "stable" performance "indepent" of the cache size, which is similar or even better than for the 512MB cache size in the currently implemented version. However, for some reason, the variance seems to be much larger than all my other plots. It might be a disk cache issue, although I'm benchmarking on a SSD, so I didn't think it would be this noticeably. Because I'm lazy and don't wanna implement repeated measurements and statistics, I ran it several times and compared the results by eye. It really seems to be runtime dependent but the first measurement with 2MB cache always seems to be the fastest.

I'm not 100% sure whether to adopt this as a fix commit to ratarmount. At least it does not change any file compatibility. I'm tendending to "yes".

> If you are using full path as the key, you will be storing the dirname for each file. This could be avoided by using something similar to an inode.

I'm not sure I understand. SQLite is a bit hard to work with hierarchical data, that's why I arrived at the current schema design which stores the full path for each file. Do you mean that I should store only the inode number + metadata (except file path) inside the SQL database and the hierarchy structure in a nested dict, which is then pickled, ... ? Imo, the file names are the most of the metadata measured in bytes, all other metadata is "only" ~8 (fields) * 32 bit =32 characters or even less depending on how well it is compressed (as far as I know, SQLite only stores the integers in as many bits as required).
