### ISSUE TITLE
Add lzip support

### ISSUE THREAD

**Issue by hohav** [mxmlnkn/ratarmount#126]
[Lzip](https://www.nongnu.org/lzip/) is a lesser-known format, but offers advantages over other formats. The ability to mount .lz files would be very nice.

**Comment by mxmlnkn** [comment]
I have stumbled upon this format a few times already but never saw it used. Are you using it or are there public datasets distributed in this format?

Like many formats in #109, it probably would be somewhat supported by libarchive. There are two issues:
 - libarchive has no fully usable Python bindings last time I checked and is therefore hard to integrate
 - I doubt that libarchive implements fast seeking for generic lzip files for the same reasons it was hard to do in gzip and xz and others, i.e., they are not indexed and even worse, lzip has a window size up to 512 MiB. Current solutions would have to store the full window size per seek point, although I'm trying to reduce that somewhat.
   - There might be hope for files produced with tarlz and plzip though because those are likely to generate smaller independent chunks that can therefore be seeked to fast.

**Comment by hohav** [comment]
I'm evaluating lzip for long-term archival purposes, and the ability to mount a large archive would be a point in its favor. But as you say it's not widely used, and there are reasonable alternatives. So waiting for support via libarchive seems perfectly reasonable, even if that's not in the cards for now. Thanks for looking into it; feel free to close the issue if that makes sense.

**Comment by mxmlnkn** [comment]
Other projects very similar to `tarlz` are [`pixz`](https://github.com/vasi/pixz) and [`t2sz`](https://github.com/martinellimarco/t2sz). They also create indexes and compress the files in the TAR independently and therefore easy to mount.

I'll leave this issue open as there might be others wanting the same.

**Comment by mxmlnkn** [comment]
@hohav I'm finished with the libarchive backend in #130 , which also supports lzip. If you want to test it out, I'd welcome feedback. That branch can be installed directly from git with:

```
python3 -m pip install --user --force-reinstall \
    'git+https://github.com/mxmlnkn/ratarmount.git@libarchive#egginfo=ratarmountcore&subdirectory=core' \
    'git+https://github.com/mxmlnkn/ratarmount.git@libarchive#egginfo=ratarmount'
```

There are some inherent performance problems with libarchive, but I tried to avoid the bigger pitfalls that e.g. archivemount suffers from.

**Comment by cheebusjeebus** [comment]
Update proper working for me, thanks mxmlnkn!
