### ISSUE TITLE
Memory leak when index+mount

### ISSUE THREAD

**Issue by ole-tange** [mxmlnkn/ratarmount#13]
I tested `ratarmount` on a tar file with 10M files. The process took around 10 GB RAM after index+mount was complete.

But if I unmounted and then mounted using the generated index, then it only took 5 GB RAM.

This suggests there is a memory leak. Maybe you are copying the data structure and never destroying a copy that you do not use when indexing?

**Comment by mxmlnkn** [comment]
Hm interesting. I don't think I can reproduce this, see:
![](https://raw.githubusercontent.com/mxmlnkn/ratarmount/master/benchmarks/plots/performance-comparison-64-MiB-metadata.png)
I guess, you used the default serialization, i.e., "custom", which has in this benchmark similar memory peak resident sizes:
```
peakVmSizeCreation  = 370552
peakRssSizeCreation = 345406
peakVmSizeLoading   = 377238
peakRssSizeLoading  = 338833
```
Or, did you use another serialization scheme?

Then again, it's not like the allocation is done manually like in C/C++, so I don't even know where to look and I can't reproduce it. It's not like there should be unused variables lying around, I'm even using slots to only allow predefined member variables for the IndexedTar class. The only significant differences should be the calls to createIndex and writeIndex. You could try simply delete the call to writeIndex, to rule that out as the cause.

In the end, this issue should become outdated after doing #12

**Comment by ole-tange** [comment]
Running:

```
mkdir z
cd z
mkdir {1..1000}
seq 1000 | parallel -X touch {}/{1..10000}
cd ..
tar cf zz.tar z
/usr/bin/time -v ratarmount zz.tar
fusermount -u zz
/usr/bin/time -v ratarmount zz.tar
fusermount -u zz
rm -rf zz zz.tar.*
```

Gives:
:
        Maximum resident set size (kbytes): 10897128
:
        Maximum resident set size (kbytes): 3742776
:

But I agree solving #12 makes this irellevant.

**Comment by mxmlnkn** [comment]
Both my plots and your shell commands, measure the peak RSS. This does not indicate leaks. *After* the init call to IndexedTar no matter whether loading or creating, the memory usage should be the same as before. I could reproduce the spike in the peak memory usage though. It seems it did not show up that significantly in my plots above because I create longer file names to pump up metadata size instead of the number of files. The plot was made for 64MiB metadata, or ~64k files with file name length of 96 characters.

[It turns out](https://web.archive.org/web/20160714075947/http://blogs.it.ox.ac.uk/inapickle/2011/06/20/high-memory-usage-when-using-pythons-tarfile-module/) that the tarfile module also stores an internal file list with metadata, ... After resetting this list on each iteration with `tarfile.members = []`, the peak RSS problem seems to be solved.

This problem and fix also affects the SQLite version.
