### ISSUE TITLE
Segmentation fault during installation with pip

### ISSUE THREAD

**Issue by baloe** [mxmlnkn/ratarmount#16]
Ubuntu 18.04.
```
bastian@laptwo ~> pip3 install --user ratarmount
Collecting ratarmount
Collecting fusepy (from ratarmount)
Collecting python-rapidjson (from ratarmount)
  Using cached https://files.pythonhosted.org/packages/61/2c/ec819d4603da706a80c4b20583b2ed7df89b6a0fc8467f090b45908f905c/python_rapidjson-0.9.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting lz4 (from ratarmount)
  Using cached https://files.pythonhosted.org/packages/5d/5e/cedd32c203ce0303188b0c7ff8388bba3c33e4bf6da21ae789962c4fb2e7/lz4-2.2.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting simplejson (from ratarmount)
Collecting indexed-gzip (from ratarmount)
  Using cached https://files.pythonhosted.org/packages/5b/e8/1472b03a6c3db08d46383b81bf1cc955752540370f4e3879acfe102bfac5/indexed_gzip-0.8.10-cp36-cp36m-manylinux1_x86_64.whl
Collecting cbor (from ratarmount)
Collecting pyyaml (from ratarmount)
Collecting msgpack (from ratarmount)
  Using cached https://files.pythonhosted.org/packages/3d/a8/e01fea81691749044a7bfd44536483a296d9c0a7ed4ec8810a229435547c/msgpack-0.6.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting ujson (from ratarmount)
Installing collected packages: fusepy, python-rapidjson, lz4, simplejson, indexed-gzip, cbor, pyyaml, msgpack, ujson, ratarmount
Successfully installed cbor-1.0.0 fusepy-3.0.1 indexed-gzip-0.8.10 lz4-2.2.1 msgpack-0.6.2 python-rapidjson-0.9.1 pyyaml-5.1.2 ratarmount-0.3.1 simplejson-3.17.0 ujson-1.35
fish: “pip3 install --user ratarmount
```” terminated by signal SIGSEGV (Address boundary error)

**Comment by mxmlnkn** [comment]
Thank you for the report.

I'v had a similar report [here](https://github.com/mxmlnkn/ratarmount/issues/7#issuecomment-557893980)

It seems that it did in fact install and you should be able to use ratarmount normally. I can't explain why it segfaults in >pip< after the installation has finished, though. Currently, I can't reproduce it, so I only can ask Google and look around, or if that does not help I'll have to revert the bzip2 support.

**Comment by mxmlnkn** [comment]
Could you provide the output of these commands?

```bash
uname -a
python3 --version
pip3 --version
python3 -m pip --version
```

If you are inclined to do so, maybe also try updating your system or just python3 and pip:
```bash
sudo apt-get update
sudo apt-get install python3-pip python3
```

And/or try upgrading pip using PyPI instead of the packaging system:
```bash
pip3 install --user --upgrade pip
python3 -m pip3 --version
```
It might be that pip3 still uses the older system-installed pip while `python3 -m pip` uses the ne installed with pip itself.

I tried to reproduce the bug with singularity:

 - Ubuntu 18.4: works without problems
 - Debian 7: singularity segfaults, probably because of some kernel mismatch problem
 - Debian 8: lz4 installation fails because of missing `no such option: --disable-pip-version-check` because python3-pip package has pip version 1.5.6-5. After `pip3 install --upgrade pip` and then using `python -m pip` instead of `pip3`, I get: the [static_assert error](https://github.com/mxmlnkn/ratarmount/issues/7#issuecomment-557926543) (will upload the fix to PyPI today), ~2k of warnings from `indexed-gzip` and one error because of missing `zlib.h`. After `apt-get install zlib1g-dev` and using the fix with the removed `static_assert`: `python3 -m pip install --user https://github.com/mxmlnkn/ratarmount/files/3884156/ratarmount-0.3.2.tar.gz`, the installation works correctly.
 - Debian 9: Works perfectly directly from debian9-slim container after only `apt-get update` and `apt-get install python3-pip`.
 
but I failed to reproduce the segfault. I also tested three other systems I've access to without encountering that bug.

Other online bugreports regarding segfault in pip:

[cffi](https://bitbucket.org/cffi/cffi/issues/272/segfault-while-installing-via-pip) -> vanished and was simply closed
[cryptography](https://github.com/pyca/cryptography/issues/3815) -> Was caused by same package being installed with apt and then tried to install with pip
[Bug at pip](https://github.com/pypa/pip/issues/5366) -> Looks like this only should occur with pip 10 and if there is pyOpenSSL installed?
[Ubuntu Bugreport](https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1821483) -> Looks like it was fixed in March 2019?

**Comment by mxmlnkn** [comment]
I've completely redone the upload to pip with automated tests and building manywheels packages on Travis and by splitting of `indexed_bzip2` written C++ from the pure Python ratarmount script. Out of curiosity, could you check if the problem persists on your system? If not, :/ I'm out of ideas and of the opinion that this is a pip bug even if my package is one of the very rare ones triggering it...

**Comment by al-zatv** [comment]
I Installed it on my ubuntu 16.04 and mount tar.bz2 file. Everything was fine on my machine (I am not the topic starter though)

**Comment by baloe** [comment]
hey @mxmlnkn, sorry I didn't get back to you any earlier.
I just ran `pip3 install --user ratarmount` and it installed flawlessly. 
Many thanks!
