### ISSUE TITLE
Request for union mount.

### ISSUE THREAD

**Issue by vrthra** [mxmlnkn/ratarmount#20]
One of the nice things about tar is that it can be used to update an already existing folder.  Currently, I mount the tar file in a separate directory, move the directory that I want the tar file to another directory, and then use `unionfs-fuse` to merge the just moved directory, and the mounted tar. 

I wish there was an easier way to do this.

**Comment by mxmlnkn** [comment]
Do I understand this correctly?

You have a normal directory:

```
/normal
+ file1
+ file2
+ dir1
    + file3
```

And the TAR contains this structure:

```
file1
file4
dir1
+ file5
```

And you want to merge the contents of the TAR inside the normal folder?

```
/normal
+ file1 (file1 from TAR and not the normal file? Or what should happen with a clash?)
+ file2
+ file4
+ dir1
  + file3
  + file5
```

It looks like you already have a solution, which could be put in a script.
Also, I'm not sure whether nor how I can access the original directory structure after I have mounted a FUSE system over that nonempty directory.
I can't promise a speedy solution on this.

**Comment by vrthra** [comment]
Thanks for the response.

>  It looks like you already have a solution, .. script

Yes, but it feels rather kludgy, and prone to unintentional breakages when the directory is not moved back after use.

> Also, I'm not sure whether nor how I can access the original directory structure after I have mounted a FUSE system over that nonempty directory.

I see. Thanks for letting me know.

**Comment by vrthra** [comment]
So, experimenting, (it seems `ratarmount` does not support a nonempty option at the moment), I found that if you have already opened the directory, (in my case, I cd'd to the directory beforehand) then the process that opened the directory will still see the old entries. It does not get overwritten by the fuse mount. So, perhaps you could open the directory before doing the mount, and use the old entries when a new entry for the same name is not found?

This is what I did (using `archivemount` since I couldn't figure out how to pass -o nonempty to ratarmount)

myfiles.tar contains the files to be placed inside mydir `x, y`.

## shell1

```
$ ls * 
myfiles.tar
mydir/
$ cd mydir/
$ ls
a
b
```

## shell2
```
$ archivemount -o nonempty myfiles.tar mydir
$ ls mydir/*
x
y
```

## Now, on shell1

```
$ ls
a
b
$ pwd
mydir
$ ls ../mydir
x
y
```

**Comment by mxmlnkn** [comment]
> This is what I did (using `archivemount` since I couldn't figure out how to pass -o nonempty to ratarmount)

```
ratarmount --fuse nonempty file.tar non-empty-folder
```

And you are right, when you are cd'ed into it, you can view the old entries in the shell after the mount, interesting.

**Comment by mxmlnkn** [comment]
I tried the thing with cd'ing into the directory to be union mounted over. However, without the `--foreground` option, FUSE seems to cd into `/` after I cd'ed into the directory, so the union mount will always show `/` and I can't seem to circumvent that. Here are some options, do you have any opinion about them?

 - Currently, ratarmount allows to union mount multiple TAR files with `ratarmount tar1 tar2 mountFolder`. I could extend this to `ratarmount folder1 folder2 tar1 tar2 mountFolder` to get a union mount of the two folders and the two TAR files into the mountFolder. By checking that the mountFolder is different from the other folders, I would ensure that I can simply access the folders to be union mounted without any cd tricks.
 - I could create a hardlink to the original folder to be mounted over. I'm not really favoring this because not all filesystems support hardlinks and even less support hardlinks to folders to avoid recursion problems.
 - I could bind mount the original folder to some temporary folder for the time ratarmount is running and then access the original folders over that temporary bind mount. However, I'm not sure how generic I can get this. [This](https://stackoverflow.com/a/29156997/2191065) might be an option.

In all cases, I don't think I'll do the union mount as a default because too much could go wrong. I guess I'll require the user to specify the folder twice if he wants to union mount it and also use it as the mount directory. However, I think I can detect this duplicate mention and then automatically add the `-o nonempty` option, so the user does not have to specify three things to get one result.

**Comment by vrthra** [comment]
Excellent! I think with the new unionmount feature. It works well. I can even use it as a superior alternative to GNU Stow! It lets me keep base configuration in a read only folder, and machine specific changes in a union mount. Thanks again for the great tool.
