### ISSUE TITLE
Awesome tool!

### ISSUE THREAD

**Issue by soichih** [mxmlnkn/ratarmount#25]
This is an amazing tool! 

I have thousands of ever-glowing-number of .tar in our storage, and I'd like to use ratarmount to access the content inside the tar files when someone makes a request (only a few tar are accessed at any given time). Since I have way too many .tar to ratarmount all simultaneously, I'd like to mount 
them on-demand, whenever there is a request made to the .tar file.

I think I can do this using autofs, but I am having trouble configuring it to work with ratarmount. Is it even possible? Basically, I'd like any request made to this directory pattern..

> /mnt/access/<id>

to automatically mount a tar file stored in 

> /mnt/archive/<id>.tar

Has anyone else tried it?

I've tried something like this in /etc/auto.ratar, but it doesn't work at all..

> ratar -fstype=fuse :ratarmount\#/mnt/wrangler/tmp/$1.tar\#$1

**Comment by mxmlnkn** [comment]
Thank you for the kind feedback.

As for what you want to do with autofs, you can't simply create `/etc/auto.ratar`, you also would have to register that file in `auto.master`, see `man auto.master`. Also, it seems, you have to do quite some handstands to get it to work. But, I got it to work on my system.

Here is what I did to get it to work. In my case I have:

```
/tmp/tars/
    /tmp/tars/mimi.tar
    /tmp/tars/momo.tar
/tmp/taraccess/
```

On access to `/tmp/taraccess/<x>/`, `/tmp/tars/<x>.tar` will be mounted to the former.

I mostly followed these documentations [[1]](https://wiki.archlinux.org/index.php/Autofs#Remote_FTP) [[2]](http://man7.org/linux/man-pages/man5/autofs.5.html) [[3]](https://serverfault.com/questions/291515/recommended-technique-for-a-custom-filesystem-mount-script).

First, in order to use a custom `-fstype=<custom>`, the executables `/sbin/mount.<custom>` and `/sbin/umount.<custom>` have to exist and behave similarly to other mount binaries, i.e., the call structure should be `mount.<custom> <mount source> <mount destination> -o <mount options>`. In our case we simply can run the pip installed executable for ratarmount but you have to watch out with permissions and the right paths because it is called by root not by the user. A naive `sudo python3 -m pip intall ratarmount` seems to do the trick but I will show how we can also setup a virtualenv for that.

Setup the virtualenv:

```bash
pip3 install --user virtualenv
cd /opt
sudo o+w .
virtualenv ratarmount-autofs.venv
sudo o-w .
. ratarmount-autofs.venv/bin/activate
python3 -m pip install ratarmount
deactivate
chmod -R go-w ratarmount-autofs.venv
sudo chown root ratarmount-autofs.venv
```

Now, you can write up `/sbin/mount.ratarmount`:

```bash
#!/bin/sh
# Arguments will be: <mount source> <mount destination> -o <options>
. /opt/ratarmount-autofs.venv/bin/activate
ratarmount $1 $2 --fuse $4
```

and `/sbin/umount.ratarmount`

```bash
#!/bin/sh
fusermount -u $1
```

Now we can add the autofs entry, which will be an executable, which returns autofs entries on-the-fly!

> The format of a master map entry is:
>
> **mount-point [map-type[,format]:]map [options]**
>
>     program
>            The map is an executable program, which is passed a key on the command
>            line and returns an entry (everything besides the key) stdout if successful.  
>            Optionally, the keyword exec may be used as a synonym for program to 
>            avoid confusion with amd formatted maps mount type program.

The mount-point is `/tmp/taraccess` and the map will be our executable script at the absolute path `/etc/auto.ratar`.

`/etc/auto.master.d/ratar.autofs`

```
/tmp/taraccess /etc/auto.ratar --timeout 60
```

`/etc/auto.ratar`

```bash
#!/bin/bash
# The first argument is the "key" in autofs terms, or simply the relative path inside the autofs watched folder
# This script is to return autofs lines in the SUN format without the leading key
# see http://man7.org/linux/man-pages/man5/autofs.5.html

key=$1
tarToMount=$( find /tmp/tars/ -type f -name "${key}.*" | head -1 )
if [[ -f $fileToMount ]]; then
    printf '%s' "-fstype=ratarmount,ro,allow_other :$tarToMount"
fi
```

So, this on-the-fly entry generating script searches for a file beginning with that key in `/tmp/tars/`, which can be `key.tar` or even `key.tar.bz2` (but even because of missing more precise checks things like `key.random-exentsion`). One thing to note about the returned line is the leading `:` before the tar to to mount, which according to the manual is necessary because it follows the `[host}:pathname` scheme or else it might get interpreted as an option, I guess.

Lastly, all scripts should be executable:

```bash
sudo chmod 755 /etc/auto.ratar /sbin/mount.ratarmount /sbin/umount.ratarmount
```

In order to debug this setup you can run autofs in the foreground similar to what ratarmount offers:

```bash
sudo automount -f -v
```

In another shell you can now do:

```bash
ls -la /tmp/taraccess/mimi/
```

which after a possibly longer mounting wait time will return:

```
dr-xr-xr-x 2 user user Mar 24 12:29 .
drwxr-xr-x 3 root root Apr  4 21:08 ..
dr-xr-xr-x 2 root root Jan  1  1970 firefox
```

for my setup. And in the other shell where automount is, you should see output like this after the minute of timeout:

```
Starting automounter version 5.1.5, master map /etc/auto.master
using kernel protocol version 5.05
mounted indirect on /tmp/taraccess with timeout 60, freq 15 seconds

attempting to mount entry /tmp/taraccess/mimi
mounted /tmp/taraccess/mimi

1 remaining in /tmp/taraccess
1 remaining in /tmp/taraccess
1 remaining in /tmp/taraccess
1 remaining in /tmp/taraccess
expiring path /tmp/taraccess/mimi
expired /tmp/taraccess/mimi
```

That should be all.

**Comment by soichih** [comment]
@mxmlnkn Thank you so much for this info! It was spot on. I was able to get ratar+autofs working!

**Comment by amerlyq** [comment]
My mind blacked out from trying to understand the autofs setup above.
Does it provide any additional benefits comparing to AVFS-like approach mentioned in #56 ?
I.e. will it become obsolete if #56 is implemented, or remain still viable usecase with (maybe) reduced scope of setup?

**Comment by mxmlnkn** [comment]
> My mind blacked out from trying to understand the autofs setup above.
> Does it provide any additional benefits comparing to AVFS-like approach mentioned in #56 ?
> I.e. will it become obsolete if #56 is implemented, or remain still viable usecase with (maybe) reduced scope of setup?

The only difference I see, is that this autofs setup starts multiple ratarmount instances which can be killed and scheduled independently making it a bit more robust in case of crashes, I guess. Having one ratarmount instance per archive might also improve performance. But, this might only be relevant in edge cases. Performance of ratarmount itself should become problematic for things like running `find` or many `stat`s in parallel.
