### ISSUE TITLE
absolute links transformed to relative links in ratarmount mount

### ISSUE THREAD

**Issue by rngadam** [mxmlnkn/ratarmount#26]
## problem

with an archive (export from a docker filesystem), I have an absolute link:

```
<path to symlink> -> /usr/bin/python
```

if I untar the archive, I see the path is absolute.

However, when I mount with ratarmount, this path is transformed into a relative path

```
<path to symlink> -> usr/bin/python
```

I would expect this to keep as a an absolute path.

## more

I'm assuming this is related to fuse rellinks vs norellinks behavior:

```
subdir=DIR

  Directory to prepend to all paths.  This option is mandatory.

rellinks

  Transform absolute symlinks into relative

norellinks

  Do not transform absolute symlinks into relative.  This is the default.
```

However I'm confused as to 1) the default is norellinks and 2) how do I pass this option using ratarmount ```--fuse```?

## workaround

instead of mount with ratarmount + rsync to a target mount, I ended up untar'ing directly into the target:

```
tar --overwrite -xvf $ARCHIVE_FILENAME -C $TARGET_MOUNT
```

**Comment by mxmlnkn** [comment]
That was totally my fault. Not sure what I was trying to do there by removing the leading slash. I pushed a new version on `develop`, which you can try out.

I also wanted to see what `rellinks` would do now but that is not a general option. It only applies to the `subdir` module, which you have to activate with `-o modules=` (or `--fuse` instead of `-o`, I guess I should have named this `-o` ...). But then the `subdir=...` option is mandatory for that module, which basically acts like mounting my own `--prefix` option. So, I guess shouldn't have bothered with that myself either ... Didn't know that at the time. And then, I presume, `rellinks` does something else, i.e., when you have a TAR file with absolute files in it and symbolic links pointing to those absolute files, then those are converted to relative links. Still have to test this, but simple absolute links to files not existing inside the TAR were not converted to relative links when using this call: `python3 ratarmount.py -c --fuse 'modules=subdir,subdir=foo,rellinks' -f -d 3 nested-symlinks.tar`.

**Comment by rngadam** [comment]
Behavior seems to be the same with develop:

```
$ pip install git+https://github.com/mxmlnkn/ratarmount.git@develop#egginfo=ratarmount
$ ratarmount --version
ratarmount 0.5.0
$ sudo ratarmount rootfs.tar /tmp/tmp.H1oh4w3jce            
Loading offset dictionary from rootfs.tar.index.sqlite took 0.00s                            
$ sudo rsync -avz /tmp/tmp.H1oh4w3jce $MOUNT
sending incremental file list
$PATH/python -> usr/bin/python
```

(also checked by mounting the archive and doing readlink)

**Comment by rngadam** [comment]
...but the archive has the absolute symlink:

```
# tar --list --verbose --file=rootfs.tar | grep python
lrwxrwxrwx 0/0               0 2020-04-08 13:32 <rel path>/bin/python -> /usr/bin/python
lrwxrwxrwx 0/0               0 2020-04-08 13:32 <rel path>/bin/python3 -> python
```

**Comment by mxmlnkn** [comment]
That can't be... The [fix](https://github.com/mxmlnkn/ratarmount/commit/5ed2d78dabced6d815502c55fcdf1c14fb9176bc) is pretty straight-forward and I tested it with [this](https://github.com/mxmlnkn/ratarmount/raw/develop/tests/symlinks.tar) example.

It looks like your are calling pip without sudo but then try to run ratarmount with sudo. It might be that you have one version installed as user and one as root. You can check with:
```
sudo which ratarmount
    /usr/local/bin/ratarmount
which ratarmount
    /home/user/.local/bin/ratarmount
```

Or else, you might try out the linked example tar above, whether that works for you (with and without sudo ratarmount).

**Comment by rngadam** [comment]
@mxmlnkn doh, you're right. sudo was using the system-wide install of ratarmount instead of my venv... Thanks!!! It's working, I can see it syncing absolute symlink now.
