### ISSUE TITLE
'SQLiteIndexedTar' object has no attribute 'tarFileName'

### ISSUE THREAD

**Issue by epicfaace** [mxmlnkn/ratarmount#52]
My code: 

```
t = SQLiteIndexedTar(fileObject=f, tarFileName="file")
```

Error:

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    t = SQLiteIndexedTar(fileObject=f, tarFileName="file")
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/beam/ratarmount.py", line 407, in __init__
    possibleIndexFilePaths = [self.tarFileName + ".index.sqlite"]
AttributeError: 'SQLiteIndexedTar' object has no attribute 'tarFileName'
```

**Comment by mxmlnkn** [comment]
As mentioned in #49, please check out the develop branch. The commit 274ec55c1b73374802ed813ddca69a1f94fc6b37 there should already fix this problem.

**Comment by epicfaace** [comment]
This issue is still present on the develop branch. https://github.com/mxmlnkn/ratarmount/pull/53/ should fix it.

**Comment by mxmlnkn** [comment]
Ah, you are right. Unfortunately, the logic there isn't the clearest. self.tarFileName is actually more like self.tarFilePath and is used in multiple locations. Also, even if no tarFileName is given but an indexFileName is given, then it should write out the index file but that is currently not the case. In the end, the fileObject input is currently unfinished. I think it was a remnant of the recursive mounting feature but now I simply call `_createIndex` on the contained file object in order to implement that.

**Comment by epicfaace** [comment]
@mxmlnkn So are you open to merging #53, in that case? It's still an issue that I'm facing when using file-like objects with ratarmount, and my PR should fix it.

**Comment by mxmlnkn** [comment]
I'll close issues now as soon as they are in master.
