### ISSUE TITLE
Reading is too slow to train neural networks

### ISSUE THREAD

**Issue by ninatu** [mxmlnkn/ratarmount#71]
Hi! 

I’ve tried to use ratarmount to train my pytorch model. I have mounted 110 tar files with 2.5M images in total (+ the same number of metafiles). But loading one image + metadata takes about  85 ms, so loading one batch of 200 images takes 17 seconds. And this does not improve with changing the number of workers in data loader… So I cannot no use ratarmount now for training...   Any advice on that?

**Comment by ninatu** [comment]
Thanks a lot for the tips! Yes, exactly I had 110 tars (without compression) and used the union mount feature to mount them to a single mount point, and multiple threads were reading data. 

I've tried to use one ratarmount instance per tar-file, and it worked! The threads read data parallelly from random mount points (I don't fix a mount point per thread), but it still scales very well as the number of threads increases. Namely, 32 threads can read a batch size of 200 for 720 ms (instead of 17 sec). 

Probably, I'll use ratarmount as Python lib later as well. Many thanks for the help!

**Comment by mxmlnkn** [comment]
Glad to hear that one of the ideas worked for you because I can't promise a speedy fix for this.

I'll still see what I can do to improve this and maybe I can get some benchmarks set up for the particular use-case of reading many small files. The most hacky idea would be to simply automate that process of spawning one FUSE process per top-level folder or something alike but it would be nicer if I could get threaded FUSE to behave nicely with sqlite3 and the Python global interpreter lock.

**Comment by mxmlnkn** [comment]
My simple tests with `find`, `xargs`, `wc`, and `stat` indicated that activating threaded FUSE actually slows things down when using `find`. I remember now that this is the reason why I dropped this. I only wanted to optimize the time for a simple `find` and it didn't improve anything.

I actually observed a ~5 times speedup when calling `wc` or `stat` from 24 threads even in non-threaded FUSE mode (the default ratarmount as it is distributed). That means, I was first confused why you didn't see any speedup at all with more workers and then it's weird that there even is a speedup when calling `xargs` with `-P 24` even in non-threaded FUSE mode and then it's too bad to see that there is no real speedup observed comparing to non-threaded FUSE mode, it even gets somewhat slower in certain cases.

I only tested with empty files because I thought that the latency is rather independent of the file contents. But it has to be noted that this implementation is not even correct because there are still race conditions to fix when multiple threads access the same file object meaning that there will be race conditions between seek and read calls. But these correctness fixes should only make it slower and shouldn't affect benchmarks with empty files because they never actually read from that shared file object.

Tests with ~87k empty files:

|                                                                                          | nothreads=True | nothreads=False |
|------------------------------------------------------------------------------------------|----------------|-----------------|
| time find mimi \| wc -l                                                                  | 4.2s           | 8.3s            |
| time find mimi/00000.tar/ -type f -print0 \| xargs -P 1 -0 -I {} stat -c %s {} \| wc -l  | 64s            | 61s             |
| time find mimi/00000.tar/ -type f -print0 \| xargs -P 1 -0 -I {} wc -c {} \| wc -l       | 48s            | 49s             |
| time find mimi/00000.tar/ -type f -print0 \| xargs -P 24 -0 -I {} stat -c %s {} \| wc -l | 20s            | 20s             |
| time find mimi/00000.tar/ -type f -print0 \| xargs -P 24 -0 -I {} wc -c {} \| wc -l      | 13s            | 13s             |

And lastly, Python's global interpreter lock might indeed be an issue but there is nothing I can do here except for rewriting the innards in something other than Python, which I actually might give a try.

**Comment by mxmlnkn** [comment]
I played around with another benchmark, which reads all files to memory. I then created two tests, one tar with 100 folders with each 1000 files with each 64kiB and another test with 100 tar-files with each 1000 files with each 64kiB and then using union-mounting. So, basically the same amount of data but one in a single TAR and the other in 100 TARs and then union mounted.

The single-tar takes 29s and the union-mounting takes 167s, so almost a 6-times slowdown.
For 100k files with 64B instead of 64kiB, loading all of them to memory took 11.5s when using a single TAR and 117s when using 100 union-mounted TARs, so roughly a slowdown of 10, which still is not the expected average slowdown of 100/2=50 but at least closer.

The problem here is the union-mount, which needs to check all specified TARs to test whether the file is inside that TAR in order to be correct if a file exists under the same name in multiple sources. In the worst case, this will slow down lookups by the number of union-mounted TARs. The single TAR is faster because all metadata are in the same SQLite database instead of being scattered in 100 different ones. Searching inside one database is O(log(n)) but if you had n database taking O(1) instead, then the complexity would worsen to O(n) instead.

The idea now is to improve this lookup by keeping a cached lookup table from the top-level folders to the mount source it belongs to. This might even be generalized by caching a fixed number of folders in a breadth-first manner. Using this approach, I could improve the time of my benchmark with 100k 64B files from 117s down to 12s.

You can try the work-in-progress performance fix by installing the develop branch via:

    python3 -m pip install --user --force-reinstall git+https://github.com/mxmlnkn/ratarmount.git@develop#egginfo=ratarmount

I would be really interested to see whether this improves your observed slowdown sufficiently. But as it is work-in-progress, it will only improve things if your separate TARs contain differently named folders.
