### ISSUE TITLE
Ratarmount preserve permission

### ISSUE THREAD

**Issue by dacorsa** [mxmlnkn/ratarmount#72]
Hi guys
i can not see directory and files in dolphin in /mnt/tarbackupmounted
but i can see in  Konsole with root permission:

dr-xr-xr-x 1 root    root       0 set 13 09:02 boot/
dr-xr-xr-x 1 root    root       0 mag 14  2020 cdrom/
dr-xr-xr-x 1 root    root       0 apr 23  2020 dev/
dr-xr-xr-x 1 root    root       0 set 13 09:04 etc/
dr-xr-xr-x 1 root    root       0 mar 20  2021 home/
dr-xr-xr-x 1 root    root       0 mag 14  2020 media/

can i use ratarmount with some option to preserve permission like original? example:
drwxr-xr-x   4 root    root    4,0K set 30 13:15 boot/
drwxr-xr-x  22 root    root    5,4K ott  4 09:13 dev/

example for other application:

archivemount -o default_permissions

can you help me?

Best regards

**Comment by dacorsa** [comment]
no way, not works:
22:04:35 root@NanoKDE /mnt # ls -la
ls: impossibile accedere a 'backup': Permesso negato
drwxr-xr-x  4 dacorsa dacorsa 4096 ott  3 21:13 ./
drwxr-xr-x 21 dacorsa dacorsa 4096 set 28 14:58 ../
d?????????  ? ?       ?          ?            ? backup/

what permission is?????

all this with command:

ratarmount -o default_permissions /home/dacorsa/backup-sda1.tar /mnt/backup/

**Comment by mxmlnkn** [comment]
The `?????` signal that you don't even have the necessary permissions to read the permissions of `backup`. That is indeed somewhat weird because ratarmount makes all files readable for all users.

Could you please tell me:
 1. What commands are you running
 2. What is the output
 3. What is the expected output

Are you concerned about permissions (rwx...) or about ownership (root or dacorsa)? The write permissions (w) are always removed because ratarmount does not support writing. The read permissions are always added for user, group, and others because the user and group IDs stored inside the TAR might not necessarily match those in your current system. E.g., if you create a TAR on one computer, move it to another, and then try to open it, the user IDs might be completely different.

**Comment by mxmlnkn** [comment]
I have an idea, what might be your problem. I assume you somehow ran `ratarmount` with `sudo` and then tried to access the mount point from a non-root user? I.e.:

    sudo ratarmount my.tar /mnt/tarbackupmounted
    ls -la /mnt/tarbackupmounted

Generally, `ratarmount` should be run without root. But, if you really have to run it with `sudo`, then try `sudo ratarmount -o allow_other`.

**Comment by dacorsa** [comment]
BINGO!
ratarmount -o allow_other /home/dacorsa/backup-sda1.tar /mnt/backup/

![immagine](https://user-images.githubusercontent.com/36949692/135965897-1dbcc3a2-6c58-4400-8f0f-1547295b4ec8.png)

i great hugs for you!

**Comment by dacorsa** [comment]
another question, with sudo doesn't find ratarmount
sudo: ratarmount: comando non trovato
why?
can i compile ratarmount to make a bin?
Thanks

**Comment by mxmlnkn** [comment]
If sudo does not find ratarmount, you simply need to install ratarmount for the root user, i.e., `sudo python3 -m pip install ratarmount`. Making a binary out of ratarmount is more complex.

**Comment by dacorsa** [comment]
ok thanks, :)
now works and it's all ok
Thanks for your work!
