### ISSUE TITLE
Index file needs to be rebuilt every time

### ISSUE THREAD

**Issue by vladfi1** [mxmlnkn/ratarmount#87]
I have a 25G tar file that takes ~4 minutes to index. However, after each reboot ratarmount needs to rebuild it:
```
Successfully loaded offset dictionary from ...
[Warning] The loaded index does not match the archive. Will recreate it.
```
I suspect this shouldn't be happening. Any ideas?

**Comment by mxmlnkn** [comment]
It should only happen when the archive changes. Can you run with `-d 3`? I hope it has some more helpful output.

**Comment by vladfi1** [comment]
Here's the output:
```
[Info] Detected compression None for file object: <_io.BufferedReader name='file.tar'>
[Info] Probably has been appended to because no EOF zero-byte blocks could be found at offset: 25790513152
[Info] Archive has probably been appended to because it is larger and more recent.
Successfully loaded offset dictionary from file.tar.index.sqlite
Loaded index file.tar.index.sqlite
[Info] Verifying metadata for 1200 files took 0.000 s
[Warning] The loaded index does not match the archive. Will recreate it.
Creating offset dictionary for file.tar ...
Creating new SQLite index database at file.tar.index.sqlite
```

**Comment by mxmlnkn** [comment]
The check looks correct. Could it be that there are multiple archives named `file.tar`? It looks like there might be a collision when determining the save-location for the index. Is there further output hinting to the same index being written to / trying to be loaded multiple times?

**Comment by vladfi1** [comment]
There's only a single `file.tar`. I don't see any further output aside from the tar being indexed again with lines like this:
```
Position 294376448 of 25790513152 (1.14%). Remaining time: 2 min 53 s (current rate), 2 min 53 s (average rate). Spent time: 0 min 2 s
```

**Comment by mxmlnkn** [comment]
Then, I'm out of ideas and I can't reproduce it to test it in depth :/. I'm not sure how much time you are willing to put in to fix this but if I could reproduce it, I would start by checking all of the check steps. As you might be able to infer from the debug output, the check algorithm inside `SQLiteIndexedTar` is somewhat like this:

 1. `loadIndex`:  Open SQLite file
 2. Load metadata. It might be helpful to take a closer look at this metadata.
    - [ ] You can manually get it by running:
    ```bash
    sqlite3 file:file.tar.index.sqlite?mode=ro 'SELECT * FROM metadata;'
    ````
    We can try to manually compare it to the actual archive's metadata: `stat file.tar`.
 4. `_checkMetadata`: This compares the stored metadata with the stat results for the archive.
    Ratarmount seems to have determined that the archive is larger and more recent than the stored metadata.
    I'd expect to either confirm this here or maybe we can see that some data is corrupted.
    - [ ] If the metadata actually looks ok, then maybe reading the metadata fails after the JSON parsing step, you would have to add debug output after the line `storedStats = json.loads(metadata['tarstats'])`
 5. `_tryToMarkAsAppended`: This is logic that came with #78. Normally, the index would be recreated on-the-spot on any size change of the archive. But, now, if it grew and is more recent it tests whether it has been appended to.
 6. `_checkIndexValidity`: It tests whether the archive has been appended by verifying a random selection of 1200 file metadata. I find it weird that even this step fails and it fails in 0.000s. This seems to indicate that there are no files in the database.
    - [ ] You can check this with `sqlite3 file:file.tar.index.sqlite?mode=ro 'SELECT COUNT(*) FROM files;'`

If there really are no files, then the question is why. The most likely reason is that it failed to create the index because it creashed or something like that.
 - [ ] After all the progress output there should be something like `Creating offset dictionary for file.tar took ... s`. Is there output like this?

You could also check whether it finished the cleanup step or not:
 - [ ] `stat file.tar.index.sqlite`
 - [ ]  `sqlite3 file:file.tar.index.sqlite?mode=ro 'SELECT name FROM sqlite_master WHERE type="table"; SELECT COUNT(*) FROM filestmp;'`

If the `filestmp` table exists, then it didn't finish creating the index correctly.
