### ISSUE TITLE
Performance in multi-process setup

### ISSUE THREAD

**Issue by Vadiml1024** [mxmlnkn/ratarmount#89]
I have a use case with multiple (>10)  processes competing to access a directory mounted by ratarmount.
I don't have exact numbers, but the total run time is **MUCH** bigger than when I run the same processes sequentially.

Reading the docs of **FUSE** I see that they support multithreading and recent versions even support splicing.
I wonder if we can use this functionality in **raratmount**?

**Comment by mxmlnkn** [comment]
Interesting, I haven't tried that yet. But reading concurrently is always a problematic case. When only a single process is accessing the mount point, it might result in sequential access but with multiple processes this will degenerate to random reads to a lot of seek in the underlying archive. That might hurt your performance. If the archive is compressed, it will **definitely** hurt your performance.

It would be interesting to know how it performs when you create a separate mount point for each process and repeat the time measurement.

I didn't know about [splicing](https://man7.org/linux/man-pages/man2/splice.2.html) at all. But, note that rarmount uses fusepy and that still is locked to FUSE 2. I tried a short time to port it to FUSE 3 because someone had that installed per default on their system but then it turned out quicker to simply build an AppImage and bundle libfuse.

But I do still want to port it to FUSE 3 and that might bring some improvements, e.g., because of asynchronous I/O. But, porting it to FUSE 3 might be complex and take a while.

**Comment by Vadiml1024** [comment]
> It would be interesting to know how it performs when you create a separate mount point for each process and repeat the time measurement.

This is exactly the plan

**Comment by Vadiml1024** [comment]
Well i have some data from the tests:
My setup is folowing ahve a directory on usb disk:
root@enka:/home/sysroot# ls -l /media/enka/Ext4-500/Test100G/ 
/media/enka/Ext4-500/Test100G/:
total 34646420
-rw-r--r-- 1 enka enka 35477926483 juin   1 15:39 bigtar100g.tar.gz

the bigtar100g.tar.gz contains:

/tmp/fsecure.mount/bigtar100g.tar.gz/:
total 98979037
drwxrwxr-x 1 sysroot sysroot           0 juin   1 14:05 level2
drwxrwxr-x 1 sysroot sysroot    67307520 juin   1 14:06 level2.tar
drwxr-xr-x 1 sysroot sysroot 10128721920 mai   31 13:30 usr1-hl-1.tar
drwxr-xr-x 1 sysroot sysroot 10128721920 mai   31 13:30 usr1-hl-2.tar
drwxr-xr-x 1 sysroot sysroot 10128721920 mai   31 13:30 usr1-hl-3.tar
drwxr-xr-x 1 sysroot sysroot 10128721920 mai   31 13:30 usr1-hl-4.tar
drwxr-xr-x 1 sysroot sysroot 10128721920 mai   31 13:30 usr1-hl-5.tar
drwxr-xr-x 1 sysroot sysroot 10128721920 mai   31 13:30 usr1-hl-6.tar
drwxr-xr-x 1 sysroot sysroot 10128721920 mai   31 13:30 usr1-hl-7.tar
drwxr-xr-x 1 sysroot sysroot 10128721920 mai   31 13:30 usr1-hl-8.tar
drwxr-xr-x 1 sysroot sysroot 10128721920 mai   31 13:30 usr1-hl-9.tar
drwxr-xr-x 1 sysroot sysroot 10128721920 mai   31 13:30 usr1.tar
drwxr-xr-x 1 sysroot sysroot           0 juil. 19  2019 vectors
root@enka:/home/sysroot# 

I user following script to launch raratmount and pass the mountpoints to dockerized anti-virus engines:

```
#!/bin/bash

avnames=(mcafee fsecure eset trend sophos kaspersky drweb clamav)
#avnames=(fsecure eset trend sophos kaspersky drweb)

ratar_depth=3

function run_ratar_mount() {
	local avname="$1"
	local dirtoscan="$2"
	local mountpoint="/tmp/${avname}.mount"
	local indexdir="/tmp/${avname}.index"


	rm -rf $indexdir
	umount $mountpoint || true
	mkdir -p $mountpoint

    echo ratarmount -P 1 --index-folders ${indexdir}  -r -l  --recursion-depth $ratar_depth  -o allow_other,ro ${dirtoscan}  ${mountpoint}
    ratarmount -P 1 --index-folders ${indexdir}  -r -l  --recursion-depth $ratar_depth  -o allow_other,ro ${dirtoscan}  ${mountpoint}
 

}

dirtoscan="$1"
echo Mounting
for av in ${avnames[@]}; do
   run_ratar_mount $av $dirtoscan
done
```

I don' t have final results yet but 3 hours after launch here is output of **ps axl**
[ps.log](https://github.com/mxmlnkn/ratarmount/files/8909924/ps.log)

It uses massive amounts of virtual and physical memory (virtual memory is in the terabytes range)
most of the CPU time is eaten by ratarmount instances.
Btw during the first hour of execution, the av engines were blocked probably waiting for ratarmount instances building the index files.

4 hours into the run:
Machine uses all available RAM and swap space:
root@enka:/home/sysroot# free -h
              total        used        free      shared  buff/cache   available
Mem:           15Gi        13Gi       178Mi        71Mi       1,5Gi       1,3Gi
Swap:          47Gi        47Gi       0,0Ki

**Comment by mxmlnkn** [comment]
I'm sorry for the late reply, I'm currently preoccupied with a [parallel gzip](https://github.com/mxmlnkn/indexed_bzip2) decoder, which coincidentally might also help alleviate your problem because you seem to test with a very large gzip file. Using ratarmount with compressed archives will work and the seeking is O(1) but the seeking is not free! And with multiple processes accessing in parallel, I think the seeks having to be done in the underlying gzip archive might explode and slow down your runtime?

The virtual memory usage seems like a non-issue to me. I'd be more concerned if it was resident memory size. I also obseved large virtual memory sizes with the zstd backend because it uses mmap on the whole input archive. But that isn't so bad because the operating system should automatically free such memory-mapped files when other programs require memory.

As far as I know the gzip backend does not mmap the input file, so my best guess is your guess that SQLite is the culprit.

As for Fuse multi-threading. I think it might actually work and might be as easy as changing `nothreads=True` to `nothreads=False` inside `ratarmount.py`. I think I already tried that and hardened the internal shared file objects against parallel access when trying to improve the performance for a simple `find`. I think I only disabled it again because I didn't see any performance benefit in that case.

**Comment by mxmlnkn** [comment]
I forgot one info: The gzip backend also has higher memory usage than e.g. bzip2 because the full 32 KiB gzip windows are held in memory for each seek point. By default the seek points are spaced apart 16 MiB but they can be configured with `--gzip-seek-point-spacing`. Also, assuming a 100 MiB/s gzip decoder, this means that seeking might take up to 16 MiB / 100 MB/s = 0.16s. And for a 100 GiB archive, this means 100 GiB / 16 MiB * 32 KiB = 200 MiB of data for the gzip windows are necessary.

**Comment by Vadiml1024** [comment]
BTW are you avaliable/interested by a payed contract to work on ratarmount enchancements?

**Comment by mxmlnkn** [comment]
That sounds like a solid plan, yes. I think it shouldn't make much of a difference performance-wise whether the SQLite database is in-memory or not. I kinda trust SQLite in that regard but benchmarks would be better. I also wanted to benchmark the use case "Squashfs or an ext4-formatted file / image mounted read-only" vs. ratarmount with an (uncompressed) TAR because someone at work has the age-old problem that the file system cannot handle millions of small files very well. This is a case for which the usage of TAR isn't mandatory because it is some archive from the internet or something like that but something that would be created by the user. But I didn't find the time to benchmark this yet as, currently, this is fully a hobby project.

I would be very interested to do this not only for self-actualization but also as a job if I didn't already have a full-time job mainly doing C++/Qt development for the HPC context with the possibility to do a PhD if I want to and if I had a nice subject I'm passionate about. I already thought about doing something related to ratarmount but it might not be novel enough. Maybe if I had a really nice use case to combine it with and could show that ratarmount can speed that up. Maybe a paper would be a better start but I'm lacking experience. That's also why I was eyeing the [AvaTar](https://www.researchgate.net/publication/340109799_AvaTar_Zero-Copy_Archiving_With_New_Kernel-Level_Operations) and [pugz](https://ieeexplore.ieee.org/abstract/document/8778385) papers with much interest because they are basically the things I'm doing with ratarmount and the work-in-progress "pragzip", a (thread) **p**arallel **ra**ndom-access **gzip** decoder to be used as replacement for `indexed_gzip`. Furthermore, similar to pugz, it would also be able to decode unknown generic gzip archives in parallel, currently, it can already do that with [`pigz` archives](https://github.com/madler/pigz/issues/36#issuecomment-1159322302), for which it already is the first and only tool to my knowledge because pugz is very much a prototype and cannot handle most kinds of data (non-ASCII). Pragzip still needs a lot of hardening and optimization though.

Note that we can also move to Telegram or Discord (see the [readme](https://github.com/mxmlnkn/ratarmount#random-access-tar-mount-ratarmount)), which already offer private chats, or something else if you want to.

**Comment by mxmlnkn** [comment]
I think we discussed this via chat and pragzip as a backend did indeed help. It can be used with ratarmount 0.12.0 via `--use-backend pragzip`.
