### ISSUE TITLE
Problem with a .zip archive with ../ in member names

### ISSUE THREAD

**Issue by Vadiml1024** [mxmlnkn/ratarmount#96]
When mounting .zip file with member names containing  **../** these members are not shown
I would suggest a cli option which simply removes  this part of the membername (as unzip command does)
I'm attaching the test file (the password is: **Orange42**)
[eicar.com.txt-encrypted.zip](https://github.com/mxmlnkn/ratarmount/files/9938944/eicar.com.txt-encrypted.zip)

**Comment by Vadiml1024** [comment]
Maybe os.path.normpath(filePath)
here:   https://github.com/mxmlnkn/ratarmount/blob/71287fa6d1afef4378a17dc1c8833c4f67ef529c/core/ratarmountcore/ZipMountSource.py#L116

Will solve the issue?

**Comment by mxmlnkn** [comment]
No. At that location, only a single name is returned. I probably should rename the variable ...

But this loop

```python3
        for file in self.files:
            file.filename = os.path.normpath(file.filename)
```

after this line:

https://github.com/mxmlnkn/ratarmount/blob/71287fa6d1afef4378a17dc1c8833c4f67ef529c/core/ratarmountcore/ZipMountSource.py#L20

fixes it mostly.

There is one case I'm not sure how to fix: I was able to create a zip file with file paths starting with `../`. In that case I cannot collapse it because I do not know the previous path. This is how I created it it:

```bash
mkdir -p root/folder otherFolder
echo foo > root/folder/bar
echo foo > otherFolder/bar
echo foo > root/bar
cd root/folder
zip ../../denormal-paths.zip ../../root/bar ../folder/bar ../../otherFolder/bar
cd ../../
zipinfo denormal-paths.zip
```

Output:

```
  adding: ../../root/bar (stored 0%)
  adding: ../folder/bar (stored 0%)
  adding: ../../otherFolder/bar (stored 0%)
Archive:  denormal-paths.zip
Zip file size: 514 bytes, number of entries: 3
-rwx------  3.0 unx        4 tx stor 22-Nov-06 19:46 ../../root/bar
-rwx------  3.0 unx        4 tx stor 22-Nov-06 19:46 ../folder/bar
-rwx------  3.0 unx        4 tx stor 22-Nov-06 19:46 ../../otherFolder/bar
3 files, 12 bytes uncompressed, 12 bytes compressed:  0.0%
```

I see these options:

 1. Remove leading `../`. Result:
   - `root/bar`
   - `folder/bar`
   - `otherFolder/bar`
 2. Collapse leading `../` with the folder right of it. Result:
   - `../bar` (Not collapsible anymore)
   - `bar`
   - `../bar` (not collapsible anymore)
 3. Add a special directory for `..`?
   - This would conserve the hierarchy encoded in the archive the best even if it is quite irregular.
   - Any name for such a special directory like `..up` could have accidental collisions with valid names.

The second option looks objectively worse. I thought of it because at first I only had the root folder but it does not generalize to multiple folders outside. The leftmost option seems ok but if the `otherFolder` was named `folder`, then there also would be a collision because the same file exists at multiple locations, which are mapped to the same one because of stripping the leading dots.

Then again, the second option is basically what automatically happens when adding files to a TAR with GNU tar. It simply strips leading `../` with a warning.

```bash
tar -c --transform 's,ufo,root/../ufo,' -f ../denormal-paths.tar ./folder/.././folder/./../ufo ../root/./bar ./././folder/../././foo
tar tvlf denormal-paths.tar
```
```
-rwx------ 1000/1000         6 2022-11-06 18:00 root/../ufo
-rwx------ 1000/1000         4 2022-11-06 18:00 root/./bar
-rwx------ 1000/1000         4 2022-11-06 18:00 ././foo
```
As can be seen here, `--transform` is not checked for such denormal paths and can be used to create test TARs.

**Comment by mxmlnkn** [comment]
And of course, it wasn't all that easy. zipfile handled the normalized filename member without problem but rarfile used it for some internal dictionary lookup, which now failed. So, I had to add the normalized path in another data structure.

It was a nice exercise to try to generate zip,rar,tar archives with these kinds of paths. But, GNU tar does not want to create a TAR archive with leading `../` or `./`. With Python's tarfile module it is easily possible but that produced TAR file throws errors with GNU tar and skips those members when trying to read it with tarfile itself. This looks like a bug in tarfile to me. Either it should also clean the path when creating the TAR, or rather in gettarinfo, or it should not skip those members.

I pushed a commit onto develop, which you can test out with:

```bash
python3 -m pip install --user --force-reinstall git+https://github.com/mxmlnkn/ratarmount.git@develop#egginfo=ratarmount
```

**Comment by Vadiml1024** [comment]
I see that you've intgreated pragzip in this branch too;
Great, i' m going to test it....
Btw i've cooked a shell script
[build-appimage.sh.txt](https://github.com/mxmlnkn/ratarmount/files/9951745/build-appimage.sh.txt)
  build-appimage  which does what in names suggests when run from docker image: *quay.io/pypa/manylinux_2_28_x86_64*
It is very useful to me as my machine is faster than github workers...
I' m attaching it...

**Comment by mxmlnkn** [comment]
> I see that you've intgreated pragzip in this branch too;

Yeah, it's still in `develop` mainly because pragzip feels not ready yet with its high upper limit for memory usage. That's what's kept me stalled for the last months. I gotta do a new ratarmount release soon...

My current thought is to hide pragzip even further behind a `--use-pragzip` option, which might get removed at some point. Or maybe I can go a step further and add a generic `--use-backend=...` option because with xz I have a similar problem with two different backends being supported and the only switch between them is depending on which is installed on the system. With pragzip hidden enough (not being the default), I would feel secure enough to do the 0.12.0 release for now.

**Comment by mxmlnkn** [comment]
> I see that you've intgreated pragzip in this branch too; Great, i' m going to test it.... Btw i've cooked a shell script [build-appimage.sh.txt](https://github.com/mxmlnkn/ratarmount/files/9951745/build-appimage.sh.txt) build-appimage which does what in names suggests when run from docker image: _quay.io/pypa/manylinux_2_28_x86_64_ It is very useful to me as my machine is faster than github workers... I' m attaching it...

The version at that time did not work yet because it used `PragzipFile.set_block_offsets`, which is now called `import_index`.

Also, I'm trying to add the script. May I ask why you added `dnf` to be installed and prefixed before `reopquery`? Was there an error without it?

I'm going to build the next AppImage with Python 3.11. I'm kinda hoping that it might benefit from the awesome promised [performance improvements](https://docs.python.org/3/whatsnew/3.11.html#whatsnew311-faster-cpython) of CPython itself.

**Comment by Vadiml1024** [comment]
About dnf --repoquery
I don't really remember the details now,  but without it the resulting image wouldn't work

**Comment by Vadiml1024** [comment]
Ahh i think i'rembember: without that hack the appimage would dynamical load fuse libaries from host system at it generate conflicts....

**Comment by mxmlnkn** [comment]
I can reproduce it with manylinux_2_28, not so with manylinux2014. It seems that yum is going to be replaced with dnf.

> [`DNF`_](https://dnf.readthedocs.io/en/latest/command_ref.html#system-message-1) is the next upcoming major version of [`YUM`_](https://dnf.readthedocs.io/en/latest/command_ref.html#system-message-2), a package manager for RPM-based Linux distributions.

**Comment by Vadiml1024** [comment]
You can probably easily adapt mt shell script to build appimage with python 3.11

**Comment by mxmlnkn** [comment]
> You can probably easily adapt mt shell script to build appimage with python 3.11

Yes, it works: https://github.com/mxmlnkn/ratarmount/blob/0dddc85ee93be29ba2005e6c361d64716e45ccc3/AppImage/build-ratarmount-appimage.sh#L115

**Comment by Vadiml1024** [comment]
Cool

**Comment by mxmlnkn** [comment]
The issue should be solved and I finally got around to doing a new release of everything (pragzip 0.4.0, indexed_bzip2 1.4.0, ratarmountcore 0.4.0, ratarmount 0.12.0).
