### ISSUE TITLE
Providing conda packages

### ISSUE THREAD

**Issue by ap--** [mxmlnkn/ratarmount#99]
Hello @mxmlnkn 

I'd like to install ratarmount via conda and wanted to ask what your thoughts are on providing conda packages. I would offer to create the required conda-forge package feedstocks to make that happen.

Packages that would need to be created:
- [x] `ratarmount` https://github.com/conda-forge/ratarmount-feedstock
- [x] `ratarmountcore` https://github.com/conda-forge/ratarmountcore-feedstock
- [x] `indexed_bzip2` https://github.com/conda-forge/indexed_bzip2-feedstock
- [x] `indexed_zstd` https://github.com/conda-forge/indexed_zstd-feedstock
- [x] `python-xz` https://github.com/conda-forge/python-xz-feedstock
- [x] `indexed_gzip` https://github.com/conda-forge/indexed_gzip-feedstock
- [x] `rarfile` https://github.com/conda-forge/rarfile-feedstock
- [x] `fusepy` https://github.com/conda-forge/fusepy-feedstock
- [x] `dataclasses` https://github.com/conda-forge/dataclasses-feedstock

Let me know what you think,
Cheers,
Andreas 😃

**Comment by mxmlnkn** [comment]
Hi there :),

I'm not opposed to uploading a conda package, I already have a pipeline for `indexed_bzip2` as you found. Those were uploaded by me. Unfortunately, I'm pretty new to the conda ecosystem and I don't use it normally.

I didn't port the `indexed_bzip2` conda CI to `pragzip` yet because the downloads were around three in total ... compared to thousands via PyPI. But, pragzip is not a required dependency yet anyway because it is not fully finished. 

Could the low download count be because it is a "personal feedstock" instead of conda-forge? I'm not sure I quite get what difference that would make for someone wanting to install ratarmount.

**Comment by mxmlnkn** [comment]
I see. Thank you for the detailed explanation.

> If you would like, I can set all of this up, and provide a few more explanations what I consider best-practice and what would help to reduce the maintainer burden, in terms of automation etc... I would start with the dependencies and make these feedstock repositories one by one.

I will take up that offer. Thank you for your help! Let me know when you need some changes in one of the projects owned by me. The other depended-on projects also had responsive maintainers the last time I reported bugs for any of them.

**Comment by ap--** [comment]
The last remaining pull request got merged! :tada: 

```
conda create -n myenv -c conda-forge ratarmount
conda activate myenv
ratarmount --help
```

Cheers,
Andreas

**Comment by mxmlnkn** [comment]
It took a while but it finally is done :tada:

Thank you for keeping at it and thank you so much for your work on this :heart: 

As the last step, I'll have to add it to the Readme. Maybe another badge and/or your posted install steps.
